<template>
  <ContentCard title="Privacy">
    <p>1. <b>Introduction</b></p>
    <p>Welcome to <b> Emeraude Portal</b>.</p>
    <p><b>Emeraude Portal</b> (“us”, “we”, or “our”) operates <b>emeraude.io</b> (hereinafter referred to as <b>“Service”</b>).</p>
    <p>Our Privacy Policy governs your visit to <b>emeraude.io</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
    <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
    <p>Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“agreement”</b>).</p>
    <p>2. <b>Definitions</b></p>
    <p><b>SERVICE</b> means the emeraude.io website operated by Emeraude Portal.</p>
    <p><b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    <p><b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
    <p><b>COOKIES</b> are small files stored on your device (computer or mobile device).</p>
    <p><b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
    <p><b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p> <p><b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.</p>
    <p><b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
    <p>3. <b>Information Collection and Use</b></p>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <p>4. <b>Types of Data Collected</b></p>
    <p>We does not collect any data. All data flow is between the web client and your application back-end</p>
    <p>6. <b>CI/CD tools</b></p>
    <p>We may use third-party Service Providers to automate the development process of our Service.</p>
    <p>7. <b>Links to Other Sites</b></p>
    <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    <p>8. <b>Changes to This Privacy Policy</b></p>
    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p>9. <b>Contact Us</b></p>
    <p>If you have any questions about this Privacy Policy, please contact us by email: <b>contact@emeraude.dev</b>.</p>
  </ContentCard>
</template>

<script lang="ts" setup>

import ContentCard from "@/components/wrappers/ContentCard.vue";
</script>

<style scoped lang="scss">
p {
  font-size: 14px;
}
</style>
